server:
  port: 8080
  context-path: #/

logging:
  level:
  tk.mybatis: DEBUG

spring:
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/test
    username: root
    password:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  mvc:
    view:
      suffix: .ftl
  freemarker:
    cache: false
    expose-request-attributes: true
    expose-spring-macro-helpers: true
    expose-session-attributes: true
    content-type: text/html;charset=utf-8
